config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :fashions

  get 'fashions/new' => 'fashions#new'
  get '/fashions' => 'fashions#top'
  get 'maps/index'
  root to: 'fashions#index'
  resources :maps, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fashion.rb
class Fashion < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :fashions, dependent: :destroy 
  validates :name, presence: true 
  validates :profile, length: { maximum: 200 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

 protected
 def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
 end
end

app/controllers/fashions_controller.rb
class FashionsController < ApplicationController
  def index
    
    if params[:search] == nil
    @fashions= Fashion.all
    elsif params[:search] == ''
    @fashions= Fashion.all
    else
    @fashions = Fashion.where("address LIKE ? ",'%' + params[:search] + '%')
    end
    @fashions = @fashions.page(params[:page]).per(3)
  end
  def new
    @fashion = Fashion.new
  end
  def create
    fashion = Fashion.new(fashion_params)
    if fashion.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end
  def show
    @fashion = Fashion.find(params[:id])
  end
  def edit
    @fashion = Fashion.find(params[:id])
  end
  def update
    fashion = Fashion.find(params[:id])
    if fashion.update(fashion_params)
      redirect_to :action => "show", :id => fashion.id
    else
      redirect_to :action => "new"
    end
  end
  def destroy
    fashion = Fashion.find(params[:id])
    fashion.destroy
    redirect_to action: :index
  end
  private
  def fashion_params
    params.require(:fashion).permit(:name, :address, :about, :image, :overall, :lat, :lng)
  end
  
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
    def index
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fashions_helper.rb
module FashionsHelper
    def getPercent(number) 
        if number.present?
          calPercent = number/5.to_f * 100
          # calPercent = number/10.to_f * 100
        
          percent = calPercent.round
        
          return percent.to_s
        else
          return 0
        end
      end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fashions/edit.html.erb
<%= form_for @fashion do |f| %>
    <%= f.label :name %>
    <%= f.label :address %>
    <%= f.label :about %>
    <%= f.label :image %>
    <%= f.text_field :name, :size => 140 %>
    <%= f.text_field :address, :size => 140 %> 
    <%= f.text_field :about, :size => 140 %> 
    <%= f.text_field :image, :size => 140 %> 
    <%= f.submit "編集する" %>
  <% end %>

app/views/fashions/index.html.erb
<section id="first-block">
    <div class="title-container">
      <%= image_tag "huku.png" %>
      <p>ReStartFashion</p><br>
    </div>
</section>
<div class="seiya">
<div class="search">
<h3>Search Post</h3>
</div>
 <%= form_tag({controller:"fashions",action:"index"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag 'search'  %>
<% end %>

<%= page_entries_info @fashions %>
<%= paginate @fashions %>

<div class="fashions-container">
<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>
  <% @fashions.each do |t| %>
    <div class="fashion">
      <div class="fashion1">
        <h>総合評価：
        <span class="star-rating">
        <span class="star-rating-front" style="width: <%= getPercent(t.overall) %>%;">★★★★★</span>
        <span class="star-rating-back">★★★★★</span>
        </span> 
        </h>
        <div class="fashion4">
        <%= t.name %>
        <%= t.address %>
        <%= t.about %>
        <%= link_to "detail", fashion_path(t.id) %>
        <%= link_to "Edit", edit_fashion_path(t.id) %>
        <%= button_to "delete", fashion_path(t.id), method: :delete %>
        </div>
      </div>
      <div class="fashion2">
        <%= image_tag t.image_url, size: "400x220" if t.image? %>
      </div>
    </div>
   
  <% end %>
  <div class="setsumei">
  <div class="setsumei1">
  <h3>About Us</h3>
</div>
  <div class="setsumei2">
  <%= image_tag "gomi.png" %>
  <p>このサイトは、多くの人に古くなった服を売るという選択肢を与えるために作りました。売れ残った服はアフリカの発展途上国へ渡り活用されていますが、活用できない量の服は処分されています。しかし、年々量が増加しており、処分できないまま山積み状態になっています。これはSDGsに関連される内容であり、改善する必要があると感じています。　そこでこのサイトを通して多くの人に、服を売れるお店を投稿していただき、環境に配慮するきっかけになるような場にしたいなと思います。ぜひ、みなさん、たくさん投稿してください！</p>
  </div>
</div>
</div>
</div>

app/views/fashions/new.html.erb
<body class ="seiya2">
<div class="seiya1">
<div class="aiueo">
<h3>NewPost</h3>
</div>
<br>
<%= form_for @fashion do |f| %>
  <div class="erena">
  <ul>
    <li><%= f.label :storename %></li>
    <li><%= f.text_field :name, :size => 70 %></li>
  </ul>
  </div>
  <div class="field2">
  <ul>
    <li><%= f.label :place %></li>
    <li><%= f.text_field :address, :size => 70 %></li>
  </ul>
  </div>
  <div class="field">
  <ul>
   <li> <%= f.label :comment  %></li>
    <li><%= f.text_area :about, :size => "80.5x2" %></li>
  </ul>
  </div>
  <div class="field">
    <%= f.label :photo %>
    <%= f.file_field :image %>
  </div>
 <div class="fashion_form">
        <li>score</li>
        <div class="post_form">
          <%= f.radio_button :overall,  5 ,id: 'star6'%>
          <label for="star6"><span class="text">５</span>★</label>
          <%= f.radio_button :overall,  4 ,id: 'star7'%>
          <label for="star7"><span class="text">４</span>★</label>
          <%= f.radio_button :overall, 3 ,id: 'star8'%>
          <label for="star8"><span class="text">３</span>★</label>
          <%= f.radio_button :overall , 2 ,id: 'star9'%>
      <label for="star9"><span class="text">２</span>★</label>
      <%= f.radio_button :overall , 1 ,id: 'star10'%>
    <label for="star10"><span class="text">１</span>★</label>
        </div>
  </div>
  <div class="actions">
   <ul>
    <li><%= f.label :lat,"緯度" %></li>
    <li> <%= f.text_field :lat,:value =>"緯度", id: :lat %></li>
  </div>
    <div class="actions">
  <ul>
    <li><%= f.label :lng,"経度" %></li>
    <li><%= f.text_field :lng,:value =>"経度", id: :lng %></li>
  </ul>
    </div>
    <br><div class="aaaaa"> <%= f.submit %></div>
  </div>
<% end %>
</div>
</body>

app/views/fashions/show.html.erb
<h3>Detail</h3>
<div class="detail">
  <div class="detail1">
  <ul>
    <li><p><%= @fashion.name %></p></li>
  </ul>
  </div>

  <div class="detai2">
  <ul>
  <li><p><%= @fashion.address %></p></li>
  </div>

  <div class="detail3">
  <ul>
  <li><p><%= @fashion.image %></p></li>
  </div>

  <div class="detail4">
  <ul>
  <li><p><%= @fashion.about %></p></li>
  </div>

  <div class="detail5">
  <ul>
  <li><p><%= @fashion.created_at %></p></li>
  </div>

  <h2>Googlemap</h2>
<input id="address" type="textbox" value="A">
<input type="button" value="Encode" onclick="codeAddress()">
<div id="display"></div>
<div id='map'></div>

<style>
#map 
{
  height: 400px;
  width: 400px;
}
</style>

<script>
let map
let geocoder
const display = document.getElementById('display')

function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 40.7828, lng:-73.9653},
    zoom: 12,
  });
  marker = new google.maps.Marker({
    position:  {lat: 40.7828, lng:-73.9653},
    map: map
  });
}

function codeAddress(){
  let inputAddress = document.getElementById('address').value;

  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
      map.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
      display.textContent = "検索結果：" + results[ 0 ].geometry.location
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}
</script>
<script src="https://maps.googleapis.com/maps/api/AIzaSyC8SlCX3UZTaZZaVZgNJ7vmBzvrujqk3nA&callback=initMap" async defer></script>

<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 100%;
}
</style>

<!-- js部分 -->
<script>
    function initMap() {

      //初期表示位置
      let latlng = new google.maps.LatLng(38.60, 139.5);
      //デザイン
      let styles = [
           {
            stylers: [
             { "saturation": 0 },
             { "lightness": 0 }
            ]
           }
          ];

      let map = new google.maps.Map(document.getElementById('map'), {
          zoom: 5.5,
          styles: styles,
          center: latlng
      });
      let transitLayer = new google.maps.TransitLayer();
      transitLayer.setMap(map);

//複数マーカー ここから
        ( function() { 
          let markerLatLng = { lat: <%= @fashion.lat %>, lng: <%= @fashion.lng %> }; // 緯度経度のデータ作成
          let marker = new google.maps.Marker({ 
            position: markerLatLng, 
            map: map 
          });
//マーカーをクリックしたとき、詳細情報を表示
          let infowindow = new google.maps.InfoWindow({
            position: markerLatLng,
            content: "<a href='<%= fashion_url(@fashion.id) %>' target='_blank'><%= @fashion.about %></a>"
          }); //ここで詳細ページへのリンクを表示させる
          marker.addListener('click', function() {
            infowindow.open(map, marker);
          });

       })();
      //複数マーカー ここまで  
  }
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC8SlCX3UZTaZZaVZgNJ7vmBzvrujqk3nA&callback=initMap" async defer></script>


</div>

<%= link_to "編集する", edit_fashion_path(@fashion.id) %>
<%= link_to "一覧に戻る", fashions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<RestartFashion>
  <head>
    <title>ReStartFashion</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>

  </head>
  
  <body>
    <header>
      <h1>ReStartFashion</h1>
      <div class="header-list">
      <ul>
     <% if user_signed_in? %>
      <li><%= button_to 'Logout', destroy_user_session_path, method: :delete %></li>
     <% else %>
      <li><%= link_to "Signup", new_user_registration_path %></li>
      <li><%= link_to "Login", new_user_session_path %></li>
      <%= link_to "NewPost", new_fashion_path %>
      <% end %>
    </ul>
   </div>
  </header>
  <main>
   <%= yield %>
  </main>
  <footer>
      <p>Copyright © ReStartFashion All Rights Reserved.</p>
    </footer>
 </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>users#show</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.fashions.each do |t| %>
  <%= t.user.name %>
  <%= t.body %>
<% end %>
<%= link_to "一覧に戻る", fashions_path %>